Test action

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -24,10 +24,10 @@ jobs:
       - name: Check for FAILURE in pytest_output.txt
         run: |
           ls test_results
-          cat test_results/pytest_output.txt
-          if grep -q 'FAILURE' test_results/pytest_output.txt; then
-            exit 1
-          fi
+          # cat test_results/pytest_output.txt
+          # if grep -q 'FAILURE' test_results/pytest_output.txt; then
+          #   exit 1
+          # fi
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v3
