Test action

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -23,10 +23,11 @@ jobs:
 
       - name: Check for FAILURE in pytest_output.txt
         run: |
-          cat ${{ github.workspace }}/test_results/pytest_output.txt
-          if grep -q 'FAILURE' ${{ github.workspace }}/test_results/pytest_output.txt; then
-            exit 1
-          fi
+          ls
+          # cat test_results/pytest_output.txt
+          # if grep -q 'FAILURE' test_results/pytest_output.txt; then
+          #   exit 1
+          # fi
 
       - name: Upload Test Results
         uses: actions/upload-artifact@v3
